-- 테이블 구조 파악
DESC EMPLOYEES; -- DESCRIBE 4글자 까지 줄일 수 있다.??

-- 1. EMOLOYEES 테이블에서 FIRST_NAME, LAST_NAME 조회하기
SELECT FIRST_NAME, LAST_NAME
  FROM HR.EMPLOYEES;

-- 2. EMPLOYEES 테이블에서 DEPARTMENT_ID를 중복 제거하고 조회
SELECT DISTINCT DEPARTMENT_ID   -- DISTINCT 중복제거 옵션
  FROM EMPLOYEES;

-- 3. EMPLOYEES 테이블에서 EMPLOYEE_ID가 150인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 150;   -- WHERE절(조건)의 등호는 비교 연산자.

-- 4. EMPLOYEES 테이블에서 SALARY가 10000 ~ 20000 사이인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 WHERE SALARY BETWEEN 10000 AND 20000;
 
-- 5. EMPLOYEES 테이블에서 DEPARTMENT_ID가 30, 40, 50인 사원 조회
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN(30, 40, 50);

-- 6. EMPLOYEES 테이블에서 DEPARTMENT_ID가 NULL인 사원 조회
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NULL;   -- IS NOT NULL

-- 7. EMPLOYEES 톄이블에서 PHONE_NUMBER가 '515'로 시작하는 사원 조회
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER     -- FROM WHERE SELECT순으로 수행하기에 별명 지정을 순서에 맞게 해야 한다. 예를 들어 순서가 3인 곳에서 별명을 지정하면 1이나 2에선 사용할 수가 없다.
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '515%';    -- 와일드 카드를 사용하려면 LIKE 연산자가 필요 (반대 상황 PHONE_NUMBER NOT LIKE '515%';)

-- 8. EMPLOYEES 테이블을 FIRST_NAME의 가나다순(오름차순:Ascending Sort)으로 정렬 조회
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 ORDER BY FIRST_NAME ASC;   -- ASC는 생략 가능

-- 9. EMPLOYEES 테이블을 높은 SALARY(내림차순:Descending Sort)를 받는 사원을 먼저 조회
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 ORDER BY SALARY DESC;

-- 10. EMPLOYEES 테이블의 사원들을 DEPARTMENT_ID순으로 조히, 동일한 DEPARTMENT_ID 가진 사원들은 높은 SALARY 순으로 조회
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
  FROM EMPLOYEES
 ORDER BY DEPARTMENT_ID ASC, SALARY DESC;