DROP TABLE ENROLL_TBL;
DROP TABLE STUDENT_TBL;
DROP TABLE SUBJECT_TBL;

CREATE TABLE STUDENT_TBL (
    STU_NO NUMBER NOT NULL,
    STU_NAME VARCHAR2(10 BYTE),
    STU_AGE NUMBER(3),
    CONSTRAINT PK_STU PRIMARY KEY(STU_NO)
);

CREATE TABLE SUBJECT_TBL (
    SUB_CODE VARCHAR2(5 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(10 BYTE),
    PROFESSOR_NAME VARCHAR2(10 BYTE),
    CONSTRAINT PK_SUB PRIMARY KEY(SUB_CODE)
);

CREATE TABLE ENROLL_TBL (
    ENROLL_NO NUMBER NOT NULL,
    STU_NO NUMBER,
    SUB_CODE VARCHAR2(5 BYTE),
    CONSTRAINT PK_ENROLL PRIMARY KEY(ENROLL_NO),
    CONSTRAINT FK_ENROLL_STU FOREIGN KEY(STU_NO) REFERENCES STUDENT_TBL(STU_NO),
    CONSTRAINT FK_ENROLL_SUB FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT_TBL(SUB_CODE)
);
